In [1]:
from io import BytesIO
from urllib import request
import numpy as np
from PIL import Image

import torch

def download_image(url):
    with request.urlopen(url) as resp:
        buffer = resp.read()
    stream = BytesIO(buffer)
    img = Image.open(stream)
    return img


def prepare_image(img, target_size):
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img = img.resize(target_size, Image.NEAREST)
    return img

In [2]:
img = download_image("https://habrastorage.org/webt/yf/_d/ok/yf_dokzqy3vcritme8ggnzqlvwa.jpeg")

In [3]:
img = prepare_image(img, (224, 224))

In [4]:
X = np.array(img.resize((224, 224)))

In [5]:
X

array([[[ 61, 104,  22],
        [ 59, 104,  23],
        [ 61, 108,  28],
        ...,
        [ 59,  88,   0],
        [ 55,  83,   0],
        [ 53,  80,   1]],

       [[ 66, 109,  29],
        [ 61, 104,  25],
        [ 65, 107,  31],
        ...,
        [ 60,  84,   0],
        [ 54,  79,   0],
        [ 55,  82,   5]],

       [[ 66, 108,  32],
        [ 66, 108,  34],
        [ 68, 108,  35],
        ...,
        [ 59,  82,   0],
        [ 61,  84,   6],
        [ 54,  78,   2]],

       ...,

       [[ 27,  49,  11],
        [ 29,  54,  14],
        [ 31,  57,  10],
        ...,
        [221, 230, 229],
        [217, 227, 226],
        [220, 230, 229]],

       [[ 26,  48,  10],
        [ 26,  51,   9],
        [ 29,  55,  10],
        ...,
        [222, 231, 230],
        [222, 234, 232],
        [227, 239, 237]],

       [[ 28,  48,  11],
        [ 23,  48,   8],
        [ 21,  46,   4],
        ...,
        [221, 231, 230],
        [226, 236, 235],
        [222, 234, 232]]

In [6]:
import torchvision.models as models

model = models.mobilenet_v2(weights='IMAGENET1K_V1')
model.eval();

In [7]:
from torchvision import transforms
train_transforms = transforms.Compose([
    transforms.Resize((200, 200)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ) # ImageNet normalization
])

In [8]:
x = train_transforms(img)

batch_t = torch.unsqueeze(x, 0)

with torch.no_grad():
    output = model(batch_t)

_, indices = torch.sort(output, descending=True)

In [9]:
indices

tensor([[585, 903, 542, 650, 819, 457, 836, 752, 971, 837, 683, 982, 948, 641,
         490, 723, 419, 610, 420, 523, 852, 487, 984, 459, 580, 589, 489, 902,
         402, 681, 834, 929, 711, 429, 432, 401, 633, 488, 552, 898, 455, 722,
         566, 916, 531, 714, 424, 907, 988, 981, 678, 793, 841, 541, 513, 594,
         785, 818, 937, 558, 638, 889, 776, 768, 911, 823, 824, 445, 456, 543,
         596, 617, 486, 737, 954, 747, 838, 265, 624, 699, 440, 315, 560, 826,
         546, 608, 620, 840, 474, 464, 622, 323, 788, 579, 740, 892, 652, 631,
         266, 872, 578, 183, 664, 574, 731, 639, 939, 409, 642, 364, 953, 504,
         221, 743, 267, 587,  61, 947, 845, 618, 733, 590, 463, 853, 568, 703,
          90, 998, 616, 843, 515, 679, 181, 480, 968, 605, 951, 591, 862, 736,
         851, 716, 696, 584, 177, 905, 629, 434, 499, 735,  55, 310, 855, 881,
         219, 418, 906, 413, 764, 599, 655, 875, 904, 813, 936, 491, 626, 522,
         712, 506, 727, 965, 201, 956, 421, 761, 160

In [10]:
from tensorflow.keras.applications.xception import preprocess_input
from tensorflow.keras.preprocessing.image import load_img

In [11]:
img = load_img('picture.jpeg', target_size=(224, 224))

In [12]:
x = np.array(img)

In [13]:
X=preprocess_input(x)
X[0]

array([[-0.52156866, -0.18431371, -0.827451  ],
       [-0.5372549 , -0.18431371, -0.81960785],
       [-0.52156866, -0.15294117, -0.78039217],
       [-0.4980392 , -0.1372549 , -0.7254902 ],
       [-0.5058824 , -0.14509803, -0.7176471 ],
       [-0.5137255 , -0.1607843 , -0.7019608 ],
       [-0.4980392 , -0.16862744, -0.6862745 ],
       [-0.5058824 , -0.17647058, -0.6784314 ],
       [-0.54509807, -0.19215685, -0.7019608 ],
       [-0.4980392 , -0.14509803, -0.654902  ],
       [-0.45098037, -0.12941176, -0.6       ],
       [-0.5294118 , -0.17647058, -0.62352943],
       [-0.5529412 , -0.17647058, -0.6313726 ],
       [-0.6       , -0.19999999, -0.64705884],
       [-0.5058824 , -0.12156862, -0.5529412 ],
       [-0.52156866, -0.15294117, -0.5764706 ],
       [-0.5529412 , -0.18431371, -0.5921569 ],
       [-0.54509807, -0.16862744, -0.5764706 ],
       [-0.56078434, -0.18431371, -0.5921569 ],
       [-0.56078434, -0.14509803, -0.5686275 ],
       [-0.62352943, -0.20784312, -0.647

In [27]:
# torch.onnx.export(
#     model,
#     dummy_input,
#     onnx_path,
#     verbose=True,
#     input_names=['input'],
#     output_names=['output'],
#     dynamic_axes={
#         'input': {0: 'batch_size'},
#         'output': {0: 'batch_size'}
#     }
# )

In [16]:
import glob
import os

# Find best checkpoint
list_of_files = glob.glob('hair_classifier_v1.onnx')
latest_file = max(list_of_files, key=os.path.getctime)
print(f"Loading model from: {latest_file}")

# Load model
model = ClothingClassifierMobileNet(size_inner=32, droprate=0.2, num_classes=10)
model.load_state_dict(torch.load(latest_file))
model.to(device)
model.eval()

Loading model from: hair_classifier_v1.onnx


NameError: name 'ClothingClassifierMobileNet' is not defined

In [17]:

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [23]:
# !pip install onnx onnxruntime-gpu 
import onnx, onnxruntime

model_name = 'hair_classifier_v1.onnx'
onnx_model = onnx.load(model_name)
onnx.checker.check_model(onnx_model)

image = Image.open('https://habrastorage.org/webt/yf/_d/ok/yf_dokzqy3vcritme8ggnzqlvwa.jpeg')
resize = transforms.Compose(
                [ transforms.Resize((200,200)), transforms.ToTensor()])             
image = resize(image)
image = image.unsqueeze(0) # add fake batch dimension
image = image.to(device)

EP_list = ['CUDAExecutionProvider', 'CPUExecutionProvider']

ort_session = onnxruntime.InferenceSession(model_name, providers=EP_list)

def to_numpy(tensor):
      return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(image)}
ort_outs = ort_session.run(None, ort_inputs)

max = float('-inf')
max_index = -1
for i in range(0, len(ort_outs[0][0])):       
   if(ort_outs[0][0][i] > max):    
       max = ort_outs[0][0][i]
       max_index = i
print(max_index)

OSError: [Errno 22] Invalid argument: 'https://habrastorage.org/webt/yf/_d/ok/yf_dokzqy3vcritme8ggnzqlvwa.jpeg'

In [19]:
# pip install onnx

In [22]:
ort_outs[0][0][0]

np.float32(2.0972447)

In [21]:
0

0

In [25]:
img2 = download_image("https://habrastorage.org/webt/yf/_d/ok/yf_dokzqy3vcritme8ggnzqlvwa.jpeg")

In [26]:
img2 = prepare_image(img2, (224, 224))

In [29]:
img2.save('picture2.jpeg')

In [30]:
# !pip install onnx onnxruntime-gpu 
import onnx, onnxruntime

model_name = 'hair_classifier_v1.onnx'
onnx_model = onnx.load(model_name)
onnx.checker.check_model(onnx_model)

image = Image.open('picture2.jpeg')
resize = transforms.Compose(
                [ transforms.Resize((200,200)), transforms.ToTensor()])             
image = resize(image)
image = image.unsqueeze(0) # add fake batch dimension
image = image.to(device)

EP_list = ['CUDAExecutionProvider', 'CPUExecutionProvider']

ort_session = onnxruntime.InferenceSession(model_name, providers=EP_list)

def to_numpy(tensor):
      return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(image)}
ort_outs = ort_session.run(None, ort_inputs)

max = float('-inf')
max_index = -1
for i in range(0, len(ort_outs[0][0])):       
   if(ort_outs[0][0][i] > max):    
       max = ort_outs[0][0][i]
       max_index = i
print(max_index)

0
